### ISSUE TITLE
Can't generate a pdf. Method 'download' not found

### ISSUE THREAD

**Issue by jlpilogistics** [sandervanhooft/laravel-invoicable#9]
I am trying to use the basic usage of this before integrating it to my project. But i can't generate pdf because method download was not found.

**Comment by sandervanhooft** [comment]
Can you elaborate how you are calling this method?

Because the method you're mentioning is there (see [here](https://github.com/sandervanhooft/laravel-invoicable/blob/1282d552df9ddced6b1a4d3254575f023330f1e4/src/Invoice.php#L116) and [here](https://github.com/sandervanhooft/laravel-invoicable/blob/1282d552df9ddced6b1a4d3254575f023330f1e4/tests/Feature/InvoiceTest.php#L104)).

**Comment by jlpilogistics** [comment]
Sorry for creating this issue. My bad. I am using an IDE and displays an error in the line of code where I use method download. But when I try to execute, everything went well. Anyway, thank you for the respone Mr. Van Hooft. Thank you also for creating this package.

**Comment by sandervanhooft** [comment]
@jlpilogistics Thanks for following up. No problem.

Can you perhaps share a screenshot of the IDE issue? Perhaps a simple docblock in the package may solve this issue for future users.
